# R 
This will be a basic overview of the `R` language. 


# Basics

Quickstart Syntax:
* R starts at 1 (not 0)
* `dataframe$column` 
* `v <- c(1,2,3,4)`


Dot notation is not the default in R, however it can be helpful as an alternative to camelcase. Given that we can just use *tab*.

In [5]:
animal.mammal.bear <- "Grizzly"
animal.mammal.rat <- "Common black"

## Variable Types
`class()` is used to determine the type.


R by default uses numeric, rather than  int, float, double, etc.


`NA` - "NULL"/etc.

`NaN` - not a number



In [10]:
as.integer(4.1)

[1] 4

In [11]:
as.numeric(4.1)

[1] 4.1

In [12]:
as.character(4.1)

[1] "4.1"

In [17]:
as.logical(4.1)

[1] TRUE

## Data Structures
* *vectors* - 1D, one data type
* *matrix* - 2D, one data type
* *array* - more than 2D, one data type
* *dataframe* - 2D, many data types
* *list* - any size, many data types

### Vector

In [57]:
v <- c(1, 245, 35)

v

[1]   1 245  35

### Matrix

In [58]:
# matrix
m <- matrix(1:25, 5, 5)
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

### Array

In [34]:
a <- array(1:50, c(5, 5, 2))
print(a[,,1])
print(a[,,2])

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    6   11   16   21
[2,]    2    7   12   17   22
[3,]    3    8   13   18   23
[4,]    4    9   14   19   24
[5,]    5   10   15   20   25
     [,1] [,2] [,3] [,4] [,5]
[1,]   26   31   36   41   46
[2,]   27   32   37   42   47
[3,]   28   33   38   43   48
[4,]   29   34   39   44   49
[5,]   30   35   40   45   50


### Dataframe

In [47]:
# dataframe
col1 <- rep("Yes", 5)
col2 <- 1:5
col3 <- TRUE 

df <- data.frame(col1, col2, col3)
names(df) <- c("Question", "id", "Bool")


df

Question id Bool
1 Yes      1  TRUE
2 Yes      2  TRUE
3 Yes      3  TRUE
4 Yes      4  TRUE
5 Yes      5  TRUE

Note the *broadcasting* with the use of `TRUE`

In [48]:
df$id

[1] 1 2 3 4 5

In [53]:
df[,1]

[1] "Yes" "Yes" "Yes" "Yes" "Yes"

In [56]:
df[1,3] <- FALSE
df

Question id Bool 
1 Yes      1  FALSE
2 Yes      2   TRUE
3 Yes      3   TRUE
4 Yes      4   TRUE
5 Yes      5   TRUE

### Lists

In [64]:
species <- c("grizzly", "panda", "black")
weight <- c(900, 600, 300)
df <- data.frame(c(1,2,3), c(FALSE, TRUE, TRUE))


l <- list(species = species, weight = weight, data=df)

l

$species
[1] "grizzly" "panda"   "black"  

$weight
[1] 900 600 300

$data
  c.1..2..3. c.FALSE..TRUE..TRUE.
1          1                FALSE
2          2                 TRUE
3          3                 TRUE

In [65]:
l[[1]]

[1] "grizzly" "panda"   "black"

## Interacting with the system

* `getwd()`
* `setwd()`
* `read.table()`
* `write.table()`
* `read.csv()`
* `write.csv()`
* `read.delim()`
* `write.delim()`

## Control flow

`break` and `next` can be used

In [78]:
if(1 < 10){
    print("1 is less than 10")
}else{
    print("no.")
}

[1] "1 is less than 10"


In [85]:
i = 0

while(i < 5){
    print(i)
    i = i + 1
}

[1] 0
[1] 1
[1] 2
[1] 3
[1] 4


In [86]:
for(n in 1:5){
    print(n)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


### Functions


In [88]:
additionFunc <- function(x, y){
    return (x + y)
}



additionFunc(1, 2)

[1] 3

## Vectorisation

Applying an operation/function across a vector, matrix, etc. rather than iterating through each element.

Create a function that *sums every element in the matrix* (without using `sum`)

In [149]:
m <- matrix(runif(1000000),1000,1000)

In [150]:
# bad method

badMatrixSum <- function(matrixIn){
    counterTotal <- 0

    row_m <- dim(matrixIn)[1]
    col_m <- dim(matrixIn)[2]

    for(x in 1:row_m){
        for(y in 1:col_m){
            counterTotal <- counterTotal + matrixIn[x, y]
        }
    }

    return(counterTotal)
    
}



# better method
betterMatrixSum <- function(matrixIn){
    rowTotal <- 0
    counterTotal <- 0
    

    row_m <- dim(matrixIn)[1]
    
    for(x in 1:row_m){

            rowTotal <- rowTotal + matrixIn[x, ]
    }
    

    for(n in 1:length(rowTotal)){
        counterTotal <- rowTotal[n] + counterTotal
    }
    
    return(counterTotal)
    
}


In [165]:
print("bad method")
system.time(badMatrixSum(m))
print("better method")
system.time(betterMatrixSum(m))
print("sum")
system.time(sum(m))

[1] "bad method"


   user  system elapsed 
  0.053   0.000   0.053 

[1] "better method"


   user  system elapsed 
  0.012   0.000   0.013 

[1] "sum"


   user  system elapsed 
  0.001   0.000   0.001 

### Apply family

* `apply` - godfather of the applys 
* `lapply` - takes and returns lists
* `sapply` - "simplify", wrapper for lapply

there are many other types, `tapply`, `mapply`, etc. 

In [172]:
m <- matrix(rnorm(100), 10, 10)

apply(m, 1, sum) # sum of each row

[1] -2.305149 -1.843913 -1.229544  2.124205 -2.647375 -3.694646 -3.830380
 [8] -2.351410  7.043121  8.033467

In [175]:
lapply(1:3, function(x) x^2)

[[1]]
[1] 1

[[2]]
[1] 4

[[3]]
[1] 9

In [176]:
sapply(1:3, function(x) x^2)

[1] 1 4 9